export enum MovementState {
  Idle = 'idle',
  Walk = 'walk',
  Run = 'run',
  Sprint = 'sprint',
  Crouch = 'crouch',
  Jump = 'jump',
  DoubleJump = 'double_jump',
  Fall = 'fall',
  WallSlide = 'wall_slide',
  WallJump = 'wall_jump',
  GroundPound = 'ground_pound',
  Dash = 'dash',
  Swim = 'swim',
  Glide = 'glide',
  LedgeGrab = 'ledge_grab',
  Slide = 'slide',
  Land = 'land',
  Dead = 'dead',
}
