export enum SoundId {
  Footstep = 'footstep',
  Jump = 'jump',
  Land = 'land',
  Coin = 'coin',
  Star = 'star',
  PowerUp = 'powerup',
  EnemyHit = 'enemy_hit',
  EnemyDefeat = 'enemy_defeat',
  PlayerHurt = 'player_hurt',
  Explosion = 'explosion',
  BossRoar = 'boss_roar',
  Checkpoint = 'checkpoint',
  Ambient = 'ambient',
  MusicMenu = 'music_menu',
  MusicLevel = 'music_level',
  MusicBoss = 'music_boss',
}
